import { useCallback, useEffect, useState } from "react";
import { ArrowDownCircle, ArrowUpCircle, Landmark, LockKeyhole, WalletCards } from "lucide-react";
import { money } from "@/lib/domain";

type Breakdown = { PIX: number; CREDIT_CARD: number; DEBIT_CARD: number; CASH: number; OTHER: number };
type CashSummary = { id: string; status: "OPEN" | "CLOSED"; openingAmount: number; openedAt: string; closedAt?: string | null; expected: Breakdown; expectedTotal: number; supplies: number; withdrawals: number; movements: { id: string; type: "SUPPLY" | "WITHDRAWAL"; amount: number; reason: string; createdAt: string }[]; closingAmount?: number | null; differenceAmount?: number | null };
const emptyBreakdown = (): Record<keyof Breakdown, string> => ({ PIX: "", CREDIT_CARD: "", DEBIT_CARD: "", CASH: "", OTHER: "" });
const labels: Record<keyof Breakdown, string> = { PIX: "Pix", CREDIT_CARD: "Crédito", DEBIT_CARD: "Débito", CASH: "Dinheiro", OTHER: "Outros" };

export function CashManagement({ establishmentId, establishmentName, canOpen, canMove, canClose, onCashChanged }: { establishmentId: string; establishmentName: string; canOpen: boolean; canMove: boolean; canClose: boolean; onCashChanged: (open: boolean) => void }) {
  const [cash, setCash] = useState<CashSummary | null>(null); const [history, setHistory] = useState<CashSummary[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [openingAmount, setOpeningAmount] = useState("0"); const [movementType, setMovementType] = useState<"SUPPLY" | "WITHDRAWAL">("WITHDRAWAL"); const [movementAmount, setMovementAmount] = useState(""); const [reason, setReason] = useState(""); const [counted, setCounted] = useState(emptyBreakdown());
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/operations/cash", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível carregar o caixa."); setCash(data.cash); setHistory(data.history ?? []); onCashChanged(Boolean(data.cash)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o caixa."); } finally { setLoading(false); } }, [onCashChanged]);
  useEffect(() => {
    void Promise.resolve().then(load);
  }, [establishmentId, load]);
  const post = async (payload: object) => { setSaving(true); setError(""); try { const response = await fetch("/api/operations/cash", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível atualizar o caixa."); await load(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível atualizar o caixa."); return false; } finally { setSaving(false); } };
  const open = async (event: React.FormEvent) => { event.preventDefault(); const amount = Number(openingAmount.replace(",", ".")); if (Number.isFinite(amount) && amount >= 0) await post({ action: "OPEN", openingAmount: amount }); };
  const move = async (event: React.FormEvent) => { event.preventDefault(); const amount = Number(movementAmount.replace(",", ".")); if (!Number.isFinite(amount) || amount <= 0 || reason.trim().length < 3) return; if (await post({ action: "MOVE", type: movementType, amount, reason: reason.trim(), idempotencyKey: crypto.randomUUID() })) { setMovementAmount(""); setReason(""); } };
  const close = async (event: React.FormEvent) => { event.preventDefault(); const values = Object.fromEntries(Object.entries(counted).map(([key, value]) => [key, Number(value.replace(",", ".")) || 0])) as Breakdown; if (await post({ action: "CLOSE", counted: values })) setCounted(emptyBreakdown()); };
  if (loading) return <div className="page-content"><div className="empty"><span>Carregando caixa…</span></div></div>;
  return <div className="page-content cash-page"><div className="hero-row"><div><span className="section-kicker">Financeiro operacional</span><h2>Caixa · {establishmentName}</h2><p>Cada operador possui sua própria sessão nesta unidade.</p></div></div>{error && <div className="auth-error">{error}</div>}
    {!cash ? <section className="cash-open-card"><div className="cash-illustration"><LockKeyhole /></div><div><span className="section-kicker">Início do turno</span><h2>O caixa está fechado</h2><p>Informe quanto existe em dinheiro para começar a receber vendas.</p></div>{canOpen ? <form onSubmit={open}><label className="field"><span>Valor inicial em dinheiro</span><div className="money-input"><span>R$</span><input inputMode="decimal" value={openingAmount} onChange={event => setOpeningAmount(event.target.value)} /></div></label><button className="primary" disabled={saving}><WalletCards />Abrir caixa</button></form> : <p>Seu perfil não possui permissão para abrir o caixa.</p>}</section> : <>
      <section className="cash-metrics"><article><span>Aberto às</span><strong>{new Date(cash.openedAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</strong><small>Valor inicial {money(cash.openingAmount)}</small></article><article><span>Movimento esperado</span><strong>{money(cash.expectedTotal)}</strong><small>Vendas e movimentações</small></article><article><span>Dinheiro disponível</span><strong>{money(cash.expected.CASH)}</strong><small>{money(cash.supplies)} suprido · {money(cash.withdrawals)} retirado</small></article></section>
      <div className="cash-grid">{canMove && <section className="panel cash-operation"><div className="cash-section-title"><div><span className="section-kicker">Movimentação</span><h2>Suprimento ou sangria</h2></div><div className="cash-toggle"><button className={movementType === "SUPPLY" ? "active" : ""} onClick={() => setMovementType("SUPPLY")}><ArrowDownCircle />Suprimento</button><button className={movementType === "WITHDRAWAL" ? "active" : ""} onClick={() => setMovementType("WITHDRAWAL")}><ArrowUpCircle />Sangria</button></div></div><form onSubmit={move}><label className="field"><span>Valor</span><div className="money-input"><span>R$</span><input inputMode="decimal" value={movementAmount} onChange={event => setMovementAmount(event.target.value)} /></div></label><label className="field"><span>Motivo obrigatório</span><input value={reason} onChange={event => setReason(event.target.value)} placeholder="Ex.: pagamento de fornecedor" /></label><button className="primary" disabled={saving}>Registrar movimentação</button></form><div className="cash-movement-list">{cash.movements.slice().reverse().map(movement => <div key={movement.id}><span className={movement.type === "SUPPLY" ? "in" : "out"}>{movement.type === "SUPPLY" ? "+" : "−"}{money(movement.amount)}</span><div><b>{movement.reason}</b><small>{new Date(movement.createdAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</small></div></div>)}</div></section>}
      {canClose && <section className="panel cash-close"><span className="section-kicker">Conferência</span><h2>Fechar caixa</h2><p>Informe os valores apurados em cada forma de pagamento.</p><form onSubmit={close}>{(Object.keys(labels) as (keyof Breakdown)[]).map(key => <label className="field" key={key}><span>{labels[key]}</span><div className="money-input"><span>R$</span><input inputMode="decimal" value={counted[key]} onChange={event => setCounted(current => ({ ...current, [key]: event.target.value }))} placeholder="0,00" /></div></label>)}<button className="primary" disabled={saving}><Landmark />Conferir e fechar</button></form></section>}</div></>}
    {history.length > 0 && <section className="panel cash-history"><span className="section-kicker">Histórico da unidade</span><h2>Últimos caixas</h2>{history.map(item => <div key={item.id}><span>{new Date(item.openedAt).toLocaleDateString("pt-BR")}</span><b>{item.status === "OPEN" ? "Aberto" : "Fechado"}</b><strong>{money(item.expectedTotal)}</strong>{item.status === "CLOSED" && <em className={(item.differenceAmount ?? 0) === 0 ? "ok" : "difference"}>Diferença {money(item.differenceAmount ?? 0)}</em>}</div>)}</section>}
  </div>;
}
