import { useCallback, useEffect, useState } from "react";
import { FlaskConical, MapPin, Plus, Trash2 } from "lucide-react";

type Product = { id: string; name: string }; type InventoryItem = { id: string; name: string; baseUnit: "GRAM" | "MILLILITER" | "UNIT" }; type ComponentDraft = { inventoryItemId: string; quantity: string; wastePercent: string }; type Recipe = { id: string; productName: string; name: string; yieldQuantity: number; components: { inventoryItemName: string; baseUnit: "GRAM" | "MILLILITER" | "UNIT"; quantity: number; wastePercent: number }[] };
const units = { GRAM: "g", MILLILITER: "ml", UNIT: "un" } as const;

export function RecipeManagement({ establishmentId, establishmentName }: { establishmentId: string; establishmentName: string }) {
  const [products, setProducts] = useState<Product[]>([]); const [inventory, setInventory] = useState<InventoryItem[]>([]); const [recipes, setRecipes] = useState<Recipe[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [productId, setProductId] = useState(""); const [name, setName] = useState(""); const [components, setComponents] = useState<ComponentDraft[]>([{ inventoryItemId: "", quantity: "", wastePercent: "0" }]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/admin/recipes", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível carregar as fichas técnicas."); setProducts(data.products); setInventory(data.inventoryItems); setRecipes(data.recipes); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar as fichas técnicas."); } finally { setLoading(false); } }, []);
  useEffect(() => {
    void establishmentId;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [establishmentId, load]);
  const updateComponent = (index: number, field: keyof ComponentDraft, value: string) => setComponents(current => current.map((component, position) => position === index ? { ...component, [field]: value } : component));
  const validComponents = components.every(component => component.inventoryItemId && Number(component.quantity.replace(",", ".")) > 0) && new Set(components.map(component => component.inventoryItemId)).size === components.length;
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!productId || name.trim().length < 2 || !validComponents) return; setSaving(true); setError(""); const payload = { productId, name: name.trim(), yieldQuantity: 1, components: components.map(component => ({ inventoryItemId: component.inventoryItemId, quantity: Number(component.quantity.replace(",", ".")), wastePercent: Number(component.wastePercent.replace(",", ".")) || 0 })) }; try { const response = await fetch("/api/admin/recipes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível cadastrar a ficha técnica."); setProductId(""); setName(""); setComponents([{ inventoryItemId: "", quantity: "", wastePercent: "0" }]); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível cadastrar a ficha técnica."); } finally { setSaving(false); } };
  return <div className="recipe-admin"><section className="panel settings-shell"><div className="settings-shell-header"><div><span className="section-kicker">Receita por unidade</span><h2>Fichas técnicas</h2><span className="active-unit-label"><MapPin />{establishmentName}</span></div><div className="settings-summary"><span><i /> Receitas ativas</span><strong>{recipes.length}</strong></div></div>
    <form className="recipe-form" onSubmit={create}><div className="recipe-basics"><label className="field"><span>Produto vendido</span><select value={productId} onChange={event => { setProductId(event.target.value); const product = products.find(item => item.id === event.target.value); if (product) setName(`Ficha — ${product.name}`); }}><option value="">Selecione</option>{products.map(product => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label className="field"><span>Nome da ficha</span><input value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: Cachorro-quente simples" /></label></div><div className="recipe-components-head"><span>Composição para uma unidade vendida</span><button type="button" onClick={() => setComponents(current => [...current, { inventoryItemId: "", quantity: "", wastePercent: "0" }])}><Plus />Adicionar item</button></div><div className="recipe-components">{components.map((component, index) => { const selected = inventory.find(item => item.id === component.inventoryItemId); return <div className="recipe-component" key={index}><label className="field"><span>Item de estoque</span><select value={component.inventoryItemId} onChange={event => updateComponent(index, "inventoryItemId", event.target.value)}><option value="">Selecione</option>{inventory.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Quantidade {selected ? `(${units[selected.baseUnit]})` : ""}</span><input inputMode="decimal" value={component.quantity} onChange={event => updateComponent(index, "quantity", event.target.value)} placeholder="0" /></label><label className="field"><span>Perda técnica (%)</span><input inputMode="decimal" value={component.wastePercent} onChange={event => updateComponent(index, "wastePercent", event.target.value)} /></label><button type="button" aria-label="Remover componente" disabled={components.length === 1} onClick={() => setComponents(current => current.filter((_, position) => position !== index))}><Trash2 /></button></div>; })}</div><button className="primary recipe-save" disabled={saving || !productId || name.trim().length < 2 || !validComponents}><FlaskConical />{saving ? "Salvando…" : "Salvar ficha técnica"}</button></form>
  </section>{error && <div className="auth-error" role="alert">{error}</div>}{loading && <div className="empty"><span>Carregando fichas…</span></div>}{!loading && recipes.length === 0 && <div className="big-empty"><FlaskConical /><h2>Nenhuma ficha técnica</h2><p>Cadastre itens de estoque e relacione-os aos produtos vendidos.</p></div>}{!loading && recipes.length > 0 && <section className="recipe-list">{recipes.map(recipe => <article key={recipe.id}><div><small>{recipe.productName}</small><strong>{recipe.name}</strong></div><span>Rende {recipe.yieldQuantity} un</span><ul>{recipe.components.map(component => <li key={component.inventoryItemName}><b>{component.inventoryItemName}</b><span>{component.quantity.toLocaleString("pt-BR")} {units[component.baseUnit]} {component.wastePercent > 0 ? `+ ${component.wastePercent}% perda` : ""}</span></li>)}</ul></article>)}</section>}</div>;
}
