"use client";

import { useCallback, useEffect, useState } from "react";

export function WhatsAppConnection({ establishmentId }: { establishmentId: string }) {
  const [data, setData] = useState<{ configured: boolean; status?: string; qr?: string } | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/admin/whatsapp", { cache: "no-store" });
      if (!response.ok) throw Error("Não foi possível consultar a conexão.");
      setData(await response.json());
      setError("");
    } catch { setError("Não foi possível consultar a conexão. Tentaremos novamente."); }
  }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [establishmentId, load]);
  async function act(action: string) {
    setSaving(true); setError("");
    try {
      const response = await fetch("/api/admin/whatsapp", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) });
      const result = await response.json(); if (!response.ok) throw Error(result.error);
      await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha na conexão."); }
    finally { setSaving(false); }
  }
  const labels: Record<string, string> = { READY: "Conectado", QR: "Leia o QR Code", CONNECTING: "Conectando…", DISCONNECTED: "Desconectado", UNAVAILABLE: "Serviço indisponível" };
  return <section className="panel settings-shell">
    <h2>WhatsApp · acesso dos clientes</h2>
    <p>Envia somente o código solicitado pelo cliente. Use um número de atendimento da unidade.</p>
    <p>Conexão não oficial: pode exigir nova leitura do QR Code ou sofrer bloqueio pelo WhatsApp. Os pedidos sem cadastro continuam disponíveis.</p>
    {!data ? <p>Carregando…</p> : !data.configured ? <p>A chave de acesso ainda precisa ser configurada para ativar o WhatsApp.</p> : <>
      <p role="status">{labels[data.status ?? ""] ?? "Desconectado"}</p>
      {data.status === "QR" && data.qr?.startsWith("data:image/png;base64,") && <>
        {/* QR is generated by our authenticated internal connector, never a remote image URL. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={data.qr} alt="QR Code para conectar o WhatsApp desta unidade" width={256} height={256} />
        <p>No WhatsApp: Aparelhos conectados → Conectar um aparelho. Este QR dá acesso à sessão; não compartilhe.</p>
      </>}
      <div style={{ display: "flex", gap: 12 }}>
        <button className="primary" disabled={saving || data.status === "READY"} onClick={() => void act("connect")}>Conectar WhatsApp</button>
        <button className="secondary" disabled={saving || data.status === "DISCONNECTED"} onClick={() => { if (confirm("Desconectar o WhatsApp? Novos códigos ficarão indisponíveis até reconectar.")) void act("disconnect"); }}>Desconectar</button>
      </div>
    </>}
    {error && <p className="auth-error" role="alert">{error}</p>}
  </section>;
}
