"use client";

import { useCallback, useEffect, useState } from "react";

export function WhatsAppConnection({ establishmentId }: { establishmentId: string }) {
  const [data, setData] = useState<{ configured: boolean; status?: string; qr?: string; orderingEnabled?: boolean } | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/admin/whatsapp", { cache: "no-store" });
      if (!response.ok) throw Error("Não foi possível consultar a conexão.");
      setData(await response.json()); setError("");
    } catch { setError("Não foi possível consultar a conexão. Tentaremos novamente."); }
  }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [establishmentId, load]);
  async function act(action: string, enabled?: boolean) {
    setSaving(true); setError("");
    try {
      const response = await fetch("/api/admin/whatsapp", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, enabled }) });
      const result = await response.json(); if (!response.ok) throw Error(result.error); await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha na conexão."); }
    finally { setSaving(false); }
  }
  const labels: Record<string, string> = { READY: "Conectado", QR: "Leia o QR Code", CONNECTING: "Conectando…", DISCONNECTED: "Desconectado", UNAVAILABLE: "Serviço indisponível" };
  const status = labels[data?.status ?? ""] ?? "Desconectado";
  const connected = data?.status === "READY";
  return <section className="panel settings-shell whatsapp-connection">
    <div className="settings-shell-header"><div><span className="section-kicker">Canal de atendimento</span><h2>WhatsApp</h2><p>Usado para o acesso do cliente e para as mensagens automáticas do delivery.</p></div>{data?.configured && <span className={`status-pill ${connected ? "status-active" : "status-inactive"}`} role="status">{status}</span>}</div>
    <div className="whatsapp-connection-note"><b>Número da unidade</b><span>Use um WhatsApp de atendimento. Ele não lê conversas e envia somente mensagens configuradas pelo sistema.</span></div>
    {!data ? <p>Carregando…</p> : !data.configured ? <p className="auth-error">A chave de acesso ainda precisa ser configurada para ativar o WhatsApp.</p> : <>
      {data.status === "QR" && data.qr?.startsWith("data:image/png;base64,") && <>
        {/* QR is generated by our authenticated internal connector, never a remote image URL. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <div className="whatsapp-qr"><img src={data.qr} alt="QR Code para conectar o WhatsApp desta unidade" width={256} height={256} /><p>No WhatsApp: <b>Aparelhos conectados → Conectar um aparelho</b>. Não compartilhe este QR.</p></div>
      </>}
<label className="whatsapp-ordering-toggle"><input type="checkbox" checked={data.orderingEnabled ?? false} disabled={saving || !connected} onChange={event => void act("set-ordering", event.target.checked)} /><span><b>Atendimento automático de pedidos</b><small>Responde por cardápio, categorias e pedido pelo WhatsApp. Produtos com opções obrigatórias levam ao pedido online.</small></span></label>
            <div className="whatsapp-connection-actions">
        <button className="primary" disabled={saving || data.status === "READY"} onClick={() => void act("connect")}>Conectar WhatsApp</button>
        <button className="secondary" disabled={saving || data.status === "DISCONNECTED"} onClick={() => { if (confirm("Desconectar o WhatsApp? Novos códigos ficarão indisponíveis até reconectar.")) void act("disconnect"); }}>Desconectar</button>
      </div>
    </>}
    {error && <p className="auth-error" role="alert">{error}</p>}
  </section>;
}
